# Generated by Django 4.2.5 on 2023-10-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
