# Generated by Django 4.2.5 on 2023-09-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_type', models.CharField(choices=[('Toys', 'Toys'), ('Sport', 'Sport'), ('Animals', 'Animals')], max_length=20)),
            ],
        ),
    ]
