# Generated by Django 4.2.5 on 2023-10-16 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
