# Generated by Django 4.2.5 on 2023-10-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_item_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='edited',
            new_name='edited_date',
        ),
    ]
