# Generated by Django 4.2.5 on 2023-10-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_edited_item_edited_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
