# Generated by Django 4.2.5 on 2023-10-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_item_edited_date'),
        ('userprofile', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.customuser'),
        ),
    ]
