# Generated by Django 4.2.5 on 2023-10-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_item_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Toys', 'Toys'), ('Sport', 'Sport'), ('Animals', 'Animals'), ('Auto', 'Auto'), ('Clothes', 'Clothes')], max_length=20),
        ),
    ]
